// Generated by scripts/generate-protocol.mjs from resources/protocol.
// Do not edit by hand.

export const KERNEL_PROTOCOL_VERSION = 9;
export const ETHER_PROTOCOL_VERSION = 2;

export const ETHER_CONTROL_MESSAGE = Object.freeze([
  "Hello",
  "Ready",
  "BusJoined",
  "BusLeft"
]);
export const ETHER_CONTROL_MESSAGE_KEY = Object.freeze({
  "Hello": 0,
  "Ready": 1,
  "BusJoined": 2,
  "BusLeft": 3
});

export const KERNEL_CONTROL_MESSAGE = Object.freeze([
  "RemoteParticipantReady",
  "InterestStarted",
  "InterestStopped",
  "ObjectsPublished",
  "ObjectsRemoved",
  "PublicationRejection",
  "ObjectsStateRequest",
  "ObjectsStateResponse",
  "TypesInfoRequest",
  "TypesInfoResponse",
  "TypesInfoRejection"
]);
export const KERNEL_CONTROL_MESSAGE_KEY = Object.freeze({
  "RemoteParticipantReady": 0,
  "InterestStarted": 1,
  "InterestStopped": 2,
  "ObjectsPublished": 3,
  "ObjectsRemoved": 4,
  "PublicationRejection": 5,
  "ObjectsStateRequest": 6,
  "ObjectsStateResponse": 7,
  "TypesInfoRequest": 8,
  "TypesInfoResponse": 9,
  "TypesInfoRejection": 10
});

export const TYPE_SPEC_RESPONSE = Object.freeze([
  "ClassSpecResponse",
  "NonClassSpecResponse"
]);

export const OS_KIND = Object.freeze([
  "windowsOs",
  "linuxOs",
  "androidOs",
  "appleOs",
  "unixOs",
  "posixOs",
  "otherOs"
]);
export const CPU_ARCH = Object.freeze([
  "x86",
  "x64",
  "arm2",
  "arm3",
  "arm4T",
  "arm5",
  "arm6T2",
  "arm6",
  "arm7",
  "arm7a",
  "arm7r",
  "arm7s",
  "arm64",
  "mips",
  "superH",
  "ppc",
  "ppc64",
  "sparc",
  "m68k",
  "otherArch"
]);
export const UNIT_CATEGORY = Object.freeze([
  "length",
  "mass",
  "time",
  "angle",
  "temperature",
  "frequency",
  "velocity",
  "angularVelocity",
  "acceleration",
  "angularAcceleration",
  "density",
  "pressure",
  "area",
  "force",
  "torque"
]);

export const INTEGRAL_TYPE = Object.freeze([
  "uint8Type",
  "int16Type",
  "uint16Type",
  "int32Type",
  "uint32Type",
  "int64Type",
  "uint64Type"
]);
export const REAL_TYPE = Object.freeze([
  "float32Type",
  "float64Type"
]);
export const NUMERIC_TYPE = Object.freeze([
  "IntegralType",
  "RealType"
]);
export const BASIC_TYPE = Object.freeze([
  "booleanType",
  "stringType",
  "durationType",
  "timestampType"
]);
export const BUILT_IN_TYPE = Object.freeze([
  "NumericType",
  "BasicType"
]);
export const TRANSPORT_MODE = Object.freeze([
  "unicast",
  "multicast",
  "confirmed"
]);
export const METHOD_CONSTNESS = Object.freeze([
  "constant",
  "nonConstant"
]);
export const PROPERTY_RELATION = Object.freeze([
  "nonPropertyRelated",
  "propertyGetter",
  "propertySetter"
]);
export const PROPERTY_CATEGORY = Object.freeze([
  "staticRW",
  "staticRO",
  "dynamicRW",
  "dynamicRO"
]);
export const CUSTOM_TYPE_DATA = Object.freeze([
  "EnumTypeSpec",
  "QuantityTypeSpec",
  "SequenceTypeSpec",
  "StructTypeSpec",
  "VariantTypeSpec",
  "AliasTypeSpec",
  "OptionalTypeSpec",
  "ClassTypeSpec"
]);
