// Generated by sen-stl-types. Do not edit.
// @ts-check

/**
 * @typedef {({
 *   count: number
 * })} CounterProperties
 */

/**
 * @typedef {{
 *   readonly state: CounterProperties,
 *   update: (patch: Partial<CounterProperties>) => unknown,
 *   set: (patch: Partial<CounterProperties>) => unknown
 * }} CounterMethodContext
 */

/**
 * @callback CounterIncrementMethod
 * @this {CounterMethodContext}
 * @param {number} delta
 * @returns {number | Promise<number>}
 */

/**
 * @typedef {({
 *   increment?: CounterIncrementMethod
 * })} CounterMethods
 */

/**
 * @typedef {({
 *   limitReached: [value: number]
 * })} CounterEvents
 */

/**
 * @typedef {{
 *   readonly name: string,
 *   readonly className: "demo.Counter",
 *   readonly snapshot: CounterProperties,
 *   readonly properties: CounterProperties,
 *   readonly methods: CounterMethods,
 *   update: (patch: Partial<CounterProperties>) => Promise<unknown>,
 *   emit: ((name: "limitReached", args: [value: number]) => Promise<unknown>),
 *   remove: () => Promise<void>
 * }} CounterObject
 */

/**
 * @typedef {{
 *   readonly name: string,
 *   readonly className: "demo.Counter",
 *   readonly snapshot: CounterProperties,
 *   get: <Name extends keyof CounterProperties>(name: Name) => Promise<CounterProperties[Name]>,
 *   set: ((name: "count", value: number) => Promise<void>),
 *   call: ((name: "increment", args: [delta: number]) => Promise<Awaited<number>>),
 *   on: ((name: "limitReached", listener: (event: {args: [value: number]}) => void) => CounterProxy) & ((name: "change:count", listener: (change: {value: number, previous: number | undefined}) => void) => CounterProxy)
 * }} CounterProxy
 */

/**
 * @typedef {{
 *   name: string,
 *   className: "demo.Counter",
 *   properties: CounterProperties,
 *   methods?: CounterMethods
 * }} Counter
 */

/**
 * Publish a demo.Counter object.
 * @param {*} sen
 * @param {string} bus
 * @param {Counter} descriptor
 * @param {object} [options]
 * @returns {Promise<CounterObject>}
 */
export async function publishCounter(sen, bus, descriptor, options) {
  return /** @type {CounterObject} */ (await sen.publish(bus, descriptor, options));
}

/**
 * Wait for a remote demo.Counter object.
 * @param {*} interest
 * @param {string | number | ((object: CounterProxy) => boolean)} selector
 * @param {object} [options]
 * @returns {Promise<CounterProxy>}
 */
export async function waitForCounter(interest, selector, options) {
  return /** @type {CounterProxy} */ (await interest.waitFor(selector, options));
}
